[2021-01-28 08:32:17,646] [WARNING] [runner.py:117:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2021-01-28 08:32:17,681] [INFO] [runner.py:355:main] cmd = /usr/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 run_seq_clas.py --model_name_or_path microsoft/DialoGPT-large --do_train --do_eval --max_seq_length 32 --per_device_train_batch_size 256 --output_dir /home/nlp/apex/experiment/seq_clas --fp16 --deepspeed ds_config.json
[2021-01-28 08:32:18,792] [INFO] [launch.py:78:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2021-01-28 08:32:18,792] [INFO] [launch.py:84:main] nnodes=1, num_local_procs=2, node_rank=0
[2021-01-28 08:32:18,792] [INFO] [launch.py:99:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2021-01-28 08:32:18,792] [INFO] [launch.py:100:main] dist_world_size=2
[2021-01-28 08:32:18,792] [INFO] [launch.py:102:main] Setting CUDA_VISIBLE_DEVICES=0,1
Traceback (most recent call last):
  File "run_seq_clas.py", line 25, in <module>
    from transformers.trainer_utils import is_main_process
ImportError: cannot import name 'is_main_process' from 'transformers.trainer_utils' (/home/nlp/.local/lib/python3.8/site-packages/transformers/trainer_utils.py)
Traceback (most recent call last):
  File "run_seq_clas.py", line 25, in <module>
    from transformers.trainer_utils import is_main_process
ImportError: cannot import name 'is_main_process' from 'transformers.trainer_utils' (/home/nlp/.local/lib/python3.8/site-packages/transformers/trainer_utils.py)
